# Analisis de los datos

In [1]:
from extraccion import minioFunctions as mf
import plotly.graph_objects as go
import pandas as pd
import numpy as np

### Caracteristicas de las variables

In [2]:
df_final = mf.bajar_fichero(mf.crear_cliente(), path_server=f"grupo3/raw/Final/final_2022.parquet", type="df")
print(f"La longitud total de los datos es de: {len(df_final)}")
print(f"Columnas: {df_final.columns}")
print('Representación de las primeras filas del dataset:')
print(df_final.head(10))

Dataframe importado correctamente
La longitud total de los datos es de: 21359
Columnas: Index(['lat', 'lon', 'frp_sum', 'frp_mean', 'count', 'date', 'date_last',
       'duration_days', 'area_ha', 'final', 'elevacion_centro', 'grados',
       'porcentaje', 'temp_mean', 'temp_max', 'temp_min', 'humidity_mean',
       'precipitation', 'wind_speed_max', 'wind_gusts_max', 'pressure_mean',
       'cloud_cover', 'radiation', 'evapotranspiration', 'sunshine_seconds',
       'NDVI', 'NDWI'],
      dtype='str')
Representación de las primeras filas del dataset:
         lat        lon  frp_sum  frp_mean  count       date date_last  \
0  34.940922  32.478487      0.0       0.0    0.0 2022-06-22       NaT
1  34.951754  32.483892      0.0       0.0    0.0 2022-04-22       NaT
2  34.959053  32.521256      0.0       0.0    0.0 2022-08-22       NaT
3  34.961834  32.444368      0.0       0.0    0.0 2022-06-22       NaT
4  34.967268  32.435256      0.0       0.0    0.0 2022-04-22       NaT
5  34.977097  32.470616      0.0       0.0    0.0 2022-07-22       NaT
6  34.980346  32.392628      0.0       0.0    0.0 2022-07-22       NaT
7  34.987872  32.542161      0.0       0.0    0.0 2022-03-22       NaT
8  34.992342  32.432700      0.0       0.0    0.0 2022-02-22       NaT
9  34.992755  32.417797      0.0       0.0    0.0 2022-09-22       NaT

   duration_days  area_ha  final  ...  precipitation  wind_speed_max  \
0            0.0      0.0      0  ...            0.0            22.8
1            0.0      0.0      0  ...            0.0             9.2
2            0.0      0.0      0  ...            0.0            13.5
3            0.0      0.0      0  ...            0.0            21.2
4            0.0      0.0      0  ...            0.0             9.2
5            0.0      0.0      0  ...            0.0            17.1
6            0.0      0.0      0  ...            0.0            17.1
7            0.0      0.0      0  ...            2.3            12.1
8            0.0      0.0      0  ...            0.5            18.4
9            0.0      0.0      0  ...            0.1            19.7

   wind_gusts_max  pressure_mean  cloud_cover  radiation  evapotranspiration  \
0            59.4          977.4          0.0      29.96                6.91
1            28.1          984.7          9.0      26.08                4.45
2            37.8          976.5         10.0      25.54                5.45
3            55.1          969.9          0.0      30.10                6.45
4            26.3          981.5         10.0      26.02                4.50
5            44.3          995.3          0.0      29.42                7.35
6            44.3          965.1          0.0      29.42                7.14
7            26.3          969.5         55.0      17.48                2.53
8            41.8          995.7         62.0      14.42                2.54
9            48.6          977.7         10.0      20.78                5.28

   sunshine_seconds      NDVI      NDWI
0          48905.72  0.146849 -0.247471
1          43309.00  0.675489 -0.593870
2          43344.84  0.101484 -0.278139
3          48925.63  0.381583 -0.356164
4          43310.73  0.526519 -0.428196
5          47712.49  0.384509 -0.389594
6          47712.49  0.207157 -0.339844
7          39843.43  0.325787 -0.285280
8          28173.11  0.391397 -0.361435
9          40061.27  0.114903 -0.229742

[10 rows x 27 columns]

In [3]:
print('Información del tipo de variables del dataset:')
df_final.info()

Información del tipo de variables del dataset:
<class 'pandas.DataFrame'>
RangeIndex: 21359 entries, 0 to 21358
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   lat                 21359 non-null  float64
 1   lon                 21359 non-null  float64
 2   frp_sum             21359 non-null  float64
 3   frp_mean            21359 non-null  float64
 4   count               21359 non-null  float64
 5   date                21359 non-null  datetime64[us]
 6   date_last           804 non-null    datetime64[us]
 7   duration_days       21359 non-null  float64
 8   area_ha             21359 non-null  float64
 9   final               21359 non-null  int64
 10  elevacion_centro    21353 non-null  float64
 11  grados              21331 non-null  float64
 12  porcentaje          21359 non-null  float64
 13  temp_mean           21276 non-null  float64
 14  temp_max            21276 non-null  float64
 15  temp_min            21276 non-null  float64
 16  humidity_mean       21276 non-null  float64
 17  precipitation       21276 non-null  float64
 18  wind_speed_max      21276 non-null  float64
 19  wind_gusts_max      21276 non-null  float64
 20  pressure_mean       21276 non-null  float64
 21  cloud_cover         21276 non-null  float64
 22  radiation           21276 non-null  float64
 23  evapotranspiration  21276 non-null  float64
 24  sunshine_seconds    21276 non-null  float64
 25  NDVI                21013 non-null  float64
 26  NDWI                21013 non-null  float64
dtypes: datetime64[us](2), float64(24), int64(1)
memory usage: 4.4 MB

In [4]:
print('Presentacion de informacion estadistica de las variables:')
df_final.describe()

Presentacion de informacion estadistica de las variables:

,lat,lon,frp_sum,frp_mean,count,date,date_last,duration_days,area_ha,final,...,precipitation,wind_speed_max,wind_gusts_max,pressure_mean,cloud_cover,radiation,evapotranspiration,sunshine_seconds,NDVI,NDWI
count,21359.000000,21359.000000,21359.000000,21359.000000,21359.000000,21359,804,21359.000000,21359.000000,21359.000000,...,21276.000000,21276.000000,21276.000000,21276.000000,21276.000000,21276.000000,21276.000000,21276.000000,21013.000000,21013.000000
mean,47.493442,14.433683,19.303945,3.239564,0.184840,2022-06-23 15:51:57.280771,2022-06-20 23:31:20.597015,0.252165,15.049719,0.037642,...,1.786412,17.004324,37.327486,971.099713,55.450461,14.289403,2.698958,30873.321864,0.363519,-0.319463
min,34.940922,-9.439134,0.000000,0.000000,0.000000,2022-01-01 00:00:00,2022-01-01 00:00:00,0.000000,0.000000,0.000000,...,0.000000,3.100000,9.000000,646.800000,0.000000,0.000000,0.000000,0.000000,-0.412065,-0.753720
25%,41.641878,4.050815,0.000000,0.000000,0.000000,2022-03-22 00:00:00,2022-03-28 00:00:00,0.000000,0.000000,0.000000,...,0.000000,12.300000,27.700000,947.500000,27.000000,7.077500,1.020000,20625.850000,0.183924,-0.442022
50%,44.877603,16.555050,0.000000,0.000000,0.000000,2022-06-20 00:00:00,2022-07-16 00:00:00,0.000000,0.000000,0.000000,...,0.000000,15.900000,35.600000,985.700000,59.000000,13.830000,2.195000,33949.560000,0.355651,-0.326124
75%,51.603160,25.749268,0.000000,0.000000,0.000000,2022-09-20 00:00:00,2022-08-08 00:00:00,0.000000,0.000000,0.000000,...,1.300000,20.600000,44.300000,1004.700000,86.000000,21.750000,4.120000,44024.177500,0.533369,-0.206653
max,70.921422,35.100523,20393.500000,607.340000,173.000000,2022-12-28 00:00:00,2022-12-30 00:00:00,297.000000,29099.900000,1.000000,...,101.200000,70.700000,117.400000,1045.800000,100.000000,31.910000,11.670000,72819.020000,0.856933,0.516408
std,8.482754,12.490039,342.223296,18.092367,2.718891,NaN,NaN,6.036758,405.788966,0.190334,...,4.481992,6.569516,13.404820,45.679955,32.975599,8.594548,2.049266,16235.649662,0.214592,0.172893

In [5]:
print('Frecuencia de las distintas variables categóricas:')
for col in df_final.columns:
    print(f'Columna: {col}')
    # print(df_final[col].value_counts(dropna=False))
    #print('Frecuencia relativa:')
    #print(df_final[col].value_counts(dropna=False, normalize=True))
    print('     Numero de valores únicos:', df_final[col].nunique())

Frecuencia de las distintas variables categóricas:
Columna: lat
     Numero de valores únicos: 21359
Columna: lon
     Numero de valores únicos: 21359
Columna: frp_sum
     Numero de valores únicos: 796
Columna: frp_mean
     Numero de valores únicos: 789
Columna: count
     Numero de valores únicos: 45
Columna: date
     Numero de valores únicos: 353
Columna: date_last
     Numero de valores únicos: 217
Columna: duration_days
     Numero de valores únicos: 53
Columna: area_ha
     Numero de valores únicos: 222
Columna: final
     Numero de valores únicos: 2
Columna: elevacion_centro
     Numero de valores únicos: 21349
Columna: grados
     Numero de valores únicos: 21328
Columna: porcentaje
     Numero de valores únicos: 21329
Columna: temp_mean
     Numero de valores únicos: 519
Columna: temp_max
     Numero de valores únicos: 566
Columna: temp_min
     Numero de valores únicos: 483
Columna: humidity_mean
     Numero de valores únicos: 89
Columna: precipitation
     Numero de valores únicos: 344
Columna: wind_speed_max
     Numero de valores únicos: 419
Columna: wind_gusts_max
     Numero de valores únicos: 266
Columna: pressure_mean
     Numero de valores únicos: 2149
Columna: cloud_cover
     Numero de valores únicos: 101
Columna: radiation
     Numero de valores únicos: 3065
Columna: evapotranspiration
     Numero de valores únicos: 933
Columna: sunshine_seconds
     Numero de valores únicos: 17043
Columna: NDVI
     Numero de valores únicos: 20948
Columna: NDWI
     Numero de valores únicos: 20957

### CORRELACIONES

In [6]:
df_corr = df_final.select_dtypes(include=[np.number])
matriz_corr = df_corr.corr()

print("Matriz de correlaciones: ")
matriz_corr

Matriz de correlaciones:

,lat,lon,frp_sum,frp_mean,count,duration_days,area_ha,final,elevacion_centro,grados,...,precipitation,wind_speed_max,wind_gusts_max,pressure_mean,cloud_cover,radiation,evapotranspiration,sunshine_seconds,NDVI,NDWI
lat,1.000000,0.225888,-0.037477,-0.076023,-0.042878,-0.021488,-0.025283,-0.076911,-0.286780,-0.241909,...,0.032945,0.019823,-0.046074,0.230975,0.322942,-0.342830,-0.358490,-0.272850,-0.083984,0.177474
lon,0.225888,1.000000,-0.042382,-0.004948,-0.042341,0.012525,-0.030248,0.005840,-0.240506,-0.220815,...,-0.048669,-0.052482,-0.120166,0.216734,-0.019137,-0.061745,-0.076306,-0.039512,-0.170122,0.168784
frp_sum,-0.037477,-0.042382,1.000000,0.349571,0.976868,0.226507,0.888982,0.285218,0.027462,0.025772,...,-0.020580,0.022608,0.031518,-0.022526,-0.050560,0.061732,0.092683,0.044942,0.001528,-0.007981
frp_mean,-0.076023,-0.004948,0.349571,1.000000,0.380272,0.196501,0.232905,0.905383,-0.012565,0.026107,...,-0.062664,0.050770,0.051421,0.025821,-0.166031,0.165126,0.222086,0.137640,-0.038591,0.003226
count,-0.042878,-0.042341,0.976868,0.380272,1.000000,0.242491,0.867346,0.343752,0.026621,0.028582,...,-0.026368,0.027854,0.037564,-0.021658,-0.065565,0.077979,0.114322,0.058010,-0.000046,-0.007720
duration_days,-0.021488,0.012525,0.226507,0.196501,0.242491,1.000000,0.279869,0.211214,-0.004292,-0.001930,...,-0.014927,0.016657,0.009532,0.007374,-0.030101,0.015382,0.017141,0.012704,-0.024519,0.025586
area_ha,-0.025283,-0.030248,0.888982,0.232905,0.867346,0.279869,1.000000,0.187529,0.018343,0.012634,...,-0.012940,0.016021,0.020321,-0.015993,-0.025021,0.033724,0.052795,0.023561,0.003118,-0.005165
final,-0.076911,0.005840,0.285218,0.905383,0.343752,0.211214,0.187529,1.000000,-0.019920,0.014590,...,-0.068804,0.045898,0.042449,0.035778,-0.179377,0.173797,0.226964,0.148543,-0.051077,0.010401
elevacion_centro,-0.286780,-0.240506,0.027462,-0.012565,0.026621,-0.004292,0.018343,-0.019920,1.000000,0.541839,...,0.039357,-0.182943,0.112686,-0.981871,-0.035244,0.101416,0.032438,0.052247,-0.055201,0.027554
grados,-0.241909,-0.220815,0.025772,0.026107,0.028582,-0.001930,0.012634,0.014590,0.541839,1.000000,...,0.055296,-0.164101,0.123093,-0.534208,-0.043365,0.080357,0.035478,0.053694,0.109290,-0.060230
porcentaje,-0.230323,-0.213330,0.024485,0.025830,0.027232,-0.001346,0.011784,0.014931,0.532570,0.996176,...,0.053562,-0.162306,0.120325,-0.524996,-0.040521,0.076482,0.032065,0.051349,0.102433,-0.053924
temp_mean,-0.414000,-0.136370,0.065635,0.153467,0.080442,0.003197,0.036010,0.154069,-0.084013,0.004525,...,-0.061098,0.034984,0.041719,0.091573,-0.363016,0.730101,0.849756,0.618443,0.411551,-0.513084
temp_max,-0.448788,-0.141935,0.068201,0.167754,0.084153,0.005947,0.037810,0.171785,-0.058429,0.010344,...,-0.107674,-0.003104,0.003565,0.074102,-0.437698,0.775061,0.876884,0.676901,0.385918,-0.496391
temp_min,-0.389211,-0.139683,0.058796,0.131711,0.071742,0.001870,0.031731,0.129343,-0.110112,0.002350,...,-0.001415,0.077606,0.082423,0.110802,-0.268422,0.635558,0.771075,0.521080,0.424466,-0.512873
humidity_mean,0.350245,0.008898,-0.093494,-0.236389,-0.116011,-0.033361,-0.056653,-0.249069,-0.094706,-0.044490,...,0.333075,-0.042301,-0.067453,0.055329,0.619091,-0.725798,-0.788188,-0.678641,-0.064997,0.173272
precipitation,0.032945,-0.048669,-0.020580,-0.062664,-0.026368,-0.014927,-0.012940,-0.068804,0.039357,0.055296,...,1.000000,0.178799,0.251237,-0.090253,0.351696,-0.260578,-0.225942,-0.350293,0.021430,-0.003322
wind_speed_max,0.019823,-0.052482,0.022608,0.050770,0.027854,0.016657,0.016021,0.045898,-0.182943,-0.164101,...,0.178799,1.000000,0.852186,0.139706,0.132709,-0.061192,0.051384,-0.088998,-0.050401,0.038496
wind_gusts_max,-0.046074,-0.120166,0.031518,0.051421,0.037564,0.009532,0.020321,0.042449,0.112686,0.123093,...,0.251237,0.852186,1.000000,-0.158091,0.127623,0.000364,0.079629,-0.047785,-0.011142,0.006277
pressure_mean,0.230975,0.216734,-0.022526,0.025821,-0.021658,0.007374,-0.015993,0.035778,-0.981871,-0.534208,...,-0.090253,0.139706,-0.158091,1.000000,-0.023810,-0.071976,-0.017537,-0.009973,0.056347,-0.028835
cloud_cover,0.322942,-0.019137,-0.050560,-0.166031,-0.065565,-0.030101,-0.025021,-0.179377,-0.035244,-0.043365,...,0.351696,0.132709,0.127623,-0.023810,1.000000,-0.614807,-0.553580,-0.686024,-0.082066,0.150587
radiation,-0.342830,-0.061745,0.061732,0.165126,0.077979,0.015382,0.033724,0.173797,0.101416,0.080357,...,-0.260578,-0.061192,0.000364,-0.071976,-0.614807,1.000000,0.923132,0.904849,0.276942,-0.387989
evapotranspiration,-0.358490,-0.076306,0.092683,0.222086,0.114322,0.017141,0.052795,0.226964,0.032438,0.035478,...,-0.225942,0.051384,0.079629,-0.017537,-0.553580,0.923132,1.000000,0.789483,0.279193,-0.397328
sunshine_seconds,-0.272850,-0.039512,0.044942,0.137640,0.058010,0.012704,0.023561,0.148543,0.052247,0.053694,...,-0.350293,-0.088998,-0.047785,-0.009973,-0.686024,0.904849,0.789483,1.000000,0.242893,-0.329535
NDVI,-0.083984,-0.170122,0.001528,-0.038591,-0.000046,-0.024519,0.003118,-0.051077,-0.055201,0.109290,...,0.021430,-0.050401,-0.011142,0.056347,-0.082066,0.276942,0.279193,0.242893,1.000000,-0.937495
NDWI,0.177474,0.168784,-0.007981,0.003226,-0.007720,0.025586,-0.005165,0.010401,0.027554,-0.060230,...,-0.003322,0.038496,0.006277,-0.028835,0.150587,-0.387989,-0.397328,-0.329535,-0.937495,1.000000

In [13]:
#Tomaremos 0.5 como umbral 
pd.set_option('display.max_columns', None)
print(f"Correlaciones más grandes:")
matriz_corr2 = matriz_corr.copy()
matriz_corr2[np.abs(matriz_corr2) <= 0.5] = np.nan
matriz_corr2

Correlaciones más grandes:

,lat,lon,frp_sum,frp_mean,count,duration_days,area_ha,final,elevacion_centro,grados,porcentaje,temp_mean,temp_max,temp_min,humidity_mean,precipitation,wind_speed_max,wind_gusts_max,pressure_mean,cloud_cover,radiation,evapotranspiration,sunshine_seconds,NDVI,NDWI
lat,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lon,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
frp_sum,NaN,NaN,1.000000,NaN,0.976868,NaN,0.888982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
frp_mean,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,0.905383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
count,NaN,NaN,0.976868,NaN,1.000000,NaN,0.867346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
duration_days,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
area_ha,NaN,NaN,0.888982,NaN,0.867346,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
final,NaN,NaN,NaN,0.905383,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
elevacion_centro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.541839,0.532570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.981871,NaN,NaN,NaN,NaN,NaN,NaN
grados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.541839,1.000000,0.996176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.534208,NaN,NaN,NaN,NaN,NaN,NaN
porcentaje,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.532570,0.996176,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.524996,NaN,NaN,NaN,NaN,NaN,NaN
temp_mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.985569,0.978373,-0.535495,NaN,NaN,NaN,NaN,NaN,0.730101,0.849756,0.618443,NaN,-0.513084
temp_max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.985569,1.000000,0.937872,-0.598398,NaN,NaN,NaN,NaN,NaN,0.775061,0.876884,0.676901,NaN,NaN
temp_min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.978373,0.937872,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.635558,0.771075,0.521080,NaN,-0.512873
humidity_mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.535495,-0.598398,NaN,1.000000,NaN,NaN,NaN,NaN,0.619091,-0.725798,-0.788188,-0.678641,NaN,NaN
precipitation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wind_speed_max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.852186,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wind_gusts_max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.852186,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pressure_mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.981871,-0.534208,-0.524996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
cloud_cover,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.619091,NaN,NaN,NaN,NaN,1.000000,-0.614807,-0.553580,-0.686024,NaN,NaN
radiation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.730101,0.775061,0.635558,-0.725798,NaN,NaN,NaN,NaN,-0.614807,1.000000,0.923132,0.904849,NaN,NaN
evapotranspiration,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.849756,0.876884,0.771075,-0.788188,NaN,NaN,NaN,NaN,-0.553580,0.923132,1.000000,0.789483,NaN,NaN
sunshine_seconds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.618443,0.676901,0.521080,-0.678641,NaN,NaN,NaN,NaN,-0.686024,0.904849,0.789483,1.000000,NaN,NaN
NDVI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,-0.937495
NDWI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.513084,NaN,-0.512873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.937495,1.000000

In [ ]:
#Lo mostramos más resumido
listas_corr = matriz_corr.unstack() # Cada variable tendrá una lista con las variables

#2 filtros: para mostrar las correlaciones más grandes y para no mostrar por ejemplo: "radiation" - "radiation"
filtro = abs(listas_corr) > 0.5
filtro2 = listas_corr.index.get_level_values(0) != listas_corr.index.get_level_values(1)
listas_corr = listas_corr[filtro & filtro2]

#Eliminamos duplicados de por ejemplo: "frp_sum" <=> "count" y "count" <=> "frp_sum"
listas_corr = listas_corr.loc[~listas_corr.index.map(frozenset).duplicated()]

corr_fuertes = listas_corr.reset_index()
corr_fuertes.columns = ['Var1', 'Var2', 'Corr']
corr_fuertes.sort_values(by = "Corr", ascending= False, inplace=True)
corr_fuertes

In [12]:

#Utilizaremos un mapa de calor
data= go.Heatmap(
    z=matriz_corr.values,                 
    x=matriz_corr.columns,               
    y=matriz_corr.index,                 

    text=matriz_corr.round(2).values,
    colorscale='RdBu_r', #Colorines agradables
    texttemplate="%{text}", #Para mostrar la correlacion encima del cuadradito
    hoverinfo="x+y+text" #Texto del gráfico interactivo
)

fig = go.Figure(data)

fig.update_layout(
    title='Matriz de correlaciones (variable respuesta => "final")',
    title_x=0.5,                        
    width=900, height=800,          
    xaxis_tickangle=-45 
)

#Lo muestra en el buscador (Aquí me daba error)
fig.show(renderer="browser")